mysite/campaign/urls.py
from django.urls import path 
from campaign import views

app_name = "campaign"

urlpatterns = [
    path("", views.CampaignListView.as_view(), name="campaign-list"),
    path("<int:pk>/", views.CampaignDetailView.as_view(), name="campaign-detail"),
    path("create/", views.CampaignCreateView.as_view(), name="campaign-create"),
    path("update/<int:pk>/", views.CampaignUpdateView.as_view(), name="campaign-update"),
    path("delete/<int:pk>/", views.CampaignDeleteView.as_view(), name="campaign-delete"),
    path("<int:campaign_id>/slot/", views.SlotListView.as_view(), name="slot-list"),
    path("slot/<int:pk>/", views.SlotDetailView.as_view(), name="slot-detail"),
    path("<int:campaign_id>/slot/create/", views.SlotCreateView.as_view(), name="slot-create"),
    path("<int:campaign_id>/slot/update/<int:pk>/", views.SlotUpdateView.as_view(), name="slot-update"),
    path("slot/delete/<int:pk>/", views.SlotDeleteView.as_view(), name="slot-delete"),
]

mysite/center/urls.py
from django.urls import path
from center import views

app_name = "center"

urlpatterns = [
    path("", views.center_list, name="list"),
    path("<int:id>/", views.center_detail, name="detail"),
    path("create/", views.create_center, name="create"),
    path("update/<int:id>/", views.update_center, name="update"),
    path("delete/<int:id>/", views.delete_center, name="delete"),
    path("<int:center_id>/storage/", views.StorageList.as_view(), name="storage-list"),
    path("storage/<int:pk>/", views.StorageDetail.as_view(), name="storage-detail"),
    path("<int:center_id>/storage/create/", views.CreateStorage.as_view(), name="storage-create"),
    path("storage/update/<int:pk>/", views.StorageUpdate.as_view(), name="storage-update"),
    path("storage/delete/<int:pk>/", views.StorageDelete.as_view(), name="storage-delete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("vaccination/", include("vaccination.urls", namespace="vaccination")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = "Book My Vaccine"
admin.site.site_title = "Book My Vaccine"
admin.site.index_title = "Admin Panel"

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/vaccination/urls.py
from django.urls import path
from vaccination import views

app_name = "vaccination"

urlpatterns = [
    path("", views.VaccinationList.as_view(), name="vaccination-list"),
    path("detail/<int:pk>/", views.VaccinationDetail.as_view(), name="vaccination-detail"),
    path("choose-vaccine/", views.ChooseVaccine.as_view(), name="choose-vaccine"),
    path("choose-campaign/<int:vaccine_id>/", views.ChooseCampaign.as_view(), name="choose-campaign"),
    path("choose-slot/<int:campaign_id>/", views.ChooseSlot.as_view(), name="choose-slot"),
    path("confirm-vaccination/<int:campaign_id>/<int:slot_id>/", views.ConfirmVaccination.as_view(), name="confirm-vaccination"),
    path("appointment-letter/<int:vaccination_id>/", views.appointment_letter, name="appointment-letter"),
    path("vaccination-certificate/<int:vaccination_id>/", views.vaccination_certificate, name="vaccination-certificate"),
    path("approve-vaccination/<int:vaccination_id>/", views.approve_vaccination, name = "approve-vaccination"),
]

mysite/mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    if request.user.is_authenticated:
        return render(request, "mysite/dashboard.html", {"user": request.user})
    return render(request, "mysite/index.html", {})

mysite/templates/mysite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}

    {% endblock title %}

  <!--    Favicon     -->
  <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />

  <!--    Bootstrap 5 CSS CDN Link  -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    crossorigin="anonymous" />

  <!--    Fontawesome Icon CDN Link-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!--    Custom CSS Link -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body>


<header class="header_wrapper">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{% static 'images/logo.png' %}" height="50">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-stream navbar-toggler-icon"></i>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav menu-navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/"><i class="fas fa-home"></i>
              Home </a>
          </li>



          <li class="nav-item">
            <a class="nav-link" href="/accounts/login/"><i class="fas fa-sign-in-alt"></i> Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/signup/"><i class="fas fa-plus"></i> Signup</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header> 

{% include "components/message.html" %}

<div class="container main-content mt-2 p-2">
    {% block content %}

    {% endblock content %}
</div>
<footer class="text-center">
    Copyright &#169 XYZ Privated Limited
  </footer>

  <!--    Bootstrap 5 JS CDN Link -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
  </script>
</body>

</html>

mysite/templates/mysite/dashboard.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Book My Vaccine</title>
{% endblock %}

{% block content %}
<div class="card mt-3">
    <div class="card-body container p-1 p-sm-2 p-md-3 p-lg-4 p-xl-5">
        <div class="row">
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'vaccine:list' %}" class="dashboard-card-link">
                                    <i class="fas fa-syringe fs-1"></i> <br>
                                    Available <br> Vaccines
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body row">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'center:list' %}" class="dashboard-card-link">
                                    <i class="fas fa-map-marker-alt fs-1"></i> <br>
                                    Vaccination <br> Center
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'campaign:campaign-list' %}" class="dashboard-card-link">
                                    <i class="fas fa-calendar fs-1"></i> <br>
                                    Current <br> Campaigns
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'vaccination:vaccination-list' %}" class="dashboard-card-link">
                                    <i class="fas fa-book-medical fs-1"></i> <br>
                                    My <br> Vaccination
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'vaccination:choose-vaccine' %}" class="dashboard-card-link">
                                    <i class="fas fa-clock fs-1"></i> <br>
                                    Schedule <br> Vaccination
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card text-dark bg-light m-1 p-1">
                    <div class="card-body">
                        <div class="d-flex flex-column text-center m-1">
                            <span>
                                <a href="{% url 'user:profile-view' %}" class="dashboard-card-link">
                                    <i class="fas fa-user fs-1"></i><br>
                                    Profile <br> Information
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

mysite/templates/mysite/index.html
{% extends 'mysite/base.html' %}
{% load static %}

{% block title %}
<title>Book My Vaccine</title>
{% endblock title %}

{% block content %}
<!--    Banner Starts Here      -->
<section id="home" class="home">
    <div class="banner_wrapper wrapper pb-0">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 order-md-1 order-2 p-5">
                    <h3>Save Life</h3>
                    <h2>Get Vaccinated</h2>
                    <p>Vaccines can lower your chance of getting certain diseases. Vaccines work with your body’snatural defenses to help you safely develop immunity to disease. This lowers your chances of getting certain diseases and suffering from their complications.
                    </p>
                    <a href="/accounts/login/"
                        class="main-btn mt-4 fill-btn">Schedule Vaccination</a>
                </div>
                <div class="col-md-6 order-md-2 order-1 mb-md-0 b-5">
                    <div class="top-right-sec">
                        <div class="banner-img">
                            <img src="{% static 'images/banner-image.png' %}" alt="Docter with Syringe">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper mt-1 pb-0">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card text-center">
                        <div class="icon-box fs-1 text-success">
                            <i class="fas fa-syringe"></i>
                        </div>
                        <h4>Vaccine</h4>
                        <p>Get different types of vaccines for various infections or disease like Covid-19, Polio, Chickenpox, Typhoid, Yellow Fever, Rabies etc.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card text-center">
                        <div class="icon-box fs-1 text-primary">
                            <i class="fas fa-map-marker-alt"></i>
                        </div>
                        <h4>Center</h4>
                        <p>Book your vaccine from your nearest vaccination center. This saves your time, money and energy for getting vaccinated as soon as possible.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card text-center">
                        <div class="icon-box fs-1 text-warning">
                            <i class="fas fa-calendar"></i>
                        </div>
                        <h4>Campaign</h4>
                        <p>Choose your desired campaign and book a slot based on your availabity. There's no need to stay on line and become a part of crowd.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--    Banner Ends Here        -->

<!--    About Starts Here       -->
<section id="about" class="about_wrapper wrapper">
    <div class="container text-center">
        <h2>Our Journey</h2>
        <p>We launched this platform on 2020 and so far, we have onboarded various hosiptals, collaborated with various local health authorities for conduction mass vaccination campaign. We are committed to make a healthy society through our platform. Our mission is to help every single organization involved in vaccination drives.
        </p>
        <div class="row">
            <div class="col-md-6 mb-md-0 mb-5">
                <div class="postion-relative">
                    <img src="{% static 'images/about-image.jpg' %}" alt="Nurse with syringe" class="about-img img-fluid">
                </div>
            </div>
            <div class="col-md-6 d-flex align-items-center justify-content-center">
                <div class="card">
                    <div class="row text-center">
                        <div class="col-6">
                            <h4>50+</h4>
                            <p>Vaccines Available</p>
                        </div>
                        <div class="col-6">
                            <h4>500+</h4>
                            <p>Vaccination Center</p>
                        </div>
                    </div>
                    <div class="row text-center mt-4">
                        <div class="col-6">
                            <h4>600+</h4>
                            <p>Campaign Created</p>
                        </div>
                        <div class="col-6">
                            <h4>5000+</h4>
                            <p>Successful Vaccination</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--    About Ends Here       -->
{% endblock content %}