mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("center/", include("center.urls", namespace="center")),
    path("vaccine/", include("vaccine.urls", namespace="vaccine")),
    path("campaign/", include("campaign.urls", namespace="campaign")),
    path("vaccination/", include("vaccination.urls", namespace="vaccination")),
    path("accounts/", include("user.urls", namespace="user")),
    path("password_reset/", authViews.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        authViews.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authViews.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authViews.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = "Book My Vaccine"
admin.site.site_title = "Book My Vaccine"
admin.site.index_title = "Admin Panel"

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile-view/", views.profile_view, name="profile-view"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verificatin_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

mysite/vaccination/urls.py
from django.urls import path
from vaccination import views

app_name = "vaccination"

urlpatterns = [
    path("", views.VaccinationList.as_view(), name="vaccination-list"),
    path("detail/<int:pk>/", views.VaccinationDetail.as_view(), name="vaccination-detail"),
    path("choose-vaccine/", views.ChooseVaccine.as_view(), name="choose-vaccine"),
    path("choose-campaign/<int:vaccine_id>/", views.ChooseCampaign.as_view(), name="choose-campaign"),
    path("choose-slot/<int:campaign_id>/", views.ChooseSlot.as_view(), name="choose-slot"),
    path("confirm-vaccination/<int:campaign_id>/<int:slot_id>/", views.ConfirmVaccination.as_view(), name="confirm-vaccination"),
    path("appointment-letter/<int:vaccination_id>/", views.appointment_letter, name="appointment-letter"),
    path("vaccination-certificate/<int:vaccination_id>/", views.vaccination_certificate, name="vaccination-certificate"),
    path("approve-vaccination/<int:vaccination_id>/", views.approve_vaccination, name = "approve-vaccination"),
]

mysite/vaccination/models.py
from django.db import models
from campaign.models import Campaign, Slot
from django.contrib.auth import get_user_model

User = get_user_model()

class Vaccination(models.Model):
    patient = models.ForeignKey(User, related_name="patient", on_delete=models.CASCADE)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    is_vaccinated = models.BooleanField(default=False)
    updated_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.patient.get_full_name() + " | " + str(self.campaign.vaccine.name)

mysite/vaccination/forms.py
from django import forms
from vaccination.models import Vaccination

class VaccinationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VaccinationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget = forms.HiddenInput()
            
    class Meta:
        model = Vaccination
        fields = ["patient", "campaign", "slot"]
        labels = {
            "campaign": "Vaccine / Center Name",
            "slot": "Date / Slot"
        }

mysite/vaccination/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from vaccine.models import Vaccine
from campaign.models import Campaign, Slot
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils import timezone
from vaccination.forms import VaccinationForm
from django.views import View
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from vaccination.models import Vaccination
from vaccination.utils import generate_pdf
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import reverse

class ChooseVaccine(LoginRequiredMixin, generic.ListView):
    model = Vaccine
    template_name = "vaccination/choose-vaccine.html"
    paginate_by = 10
    ordering = ["name"]


class ChooseCampaign(LoginRequiredMixin, generic.ListView):
    model = Campaign
    template_name = "vaccination/choose-campaign.html"
    paginate_by = 10
    ordering = ["start_date"]

    def get_queryset(self):
        return super().get_queryset().filter(vaccine = self.kwargs["vaccine_id"])


class ChooseSlot(LoginRequiredMixin, generic.ListView):
    model = Slot
    template_name = "vaccination/choose-slot.html"
    paginate_by = 10
    ordering = ["date"]

    def get_queryset(self):
        return super().get_queryset().filter(campaign = self.kwargs["campaign_id"], date__gte = timezone.now())


class ConfirmVaccination(View):
    form_class = VaccinationForm

    def get(self, request, *args, **kwargs):
        campaign = Campaign.objects.get(id = self.kwargs["campaign_id"])
        slot = Slot.objects.get(id=self.kwargs["slot_id"])
        form = self.form_class(initial={
            "patient": request.user,
            "campaign": campaign,
            "slot": slot,
        })
        context = {
            "patient": request.user,
            "campaign": campaign,
            "slot": slot,
            "form": form,
        }
        return render(request, "vaccination/confirm-vaccination.html", context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            is_reserved = Slot.reserve_vaccine(self.kwargs["campaign_id"], self.kwargs["slot_id"])
            if is_reserved:
                form.save()
                return HttpResponse("Your vaccination has been scheduled.")
            return HttpResponseBadRequest("Unable to reserve vaccine at this moment")
        return HttpResponseBadRequest("Invalid Form Data")


class VaccinationList(LoginRequiredMixin, generic.ListView):
    model = Vaccination
    template_name = "vaccination/vaccination-list.html"
    paginate_by = 10
    ordering = ["id"]

    def get_queryset(self):
        return super().get_queryset().filter(patient = self.request.user)


class VaccinationDetail(LoginRequiredMixin, generic.DetailView):
    model = Vaccination
    template_name = "vaccination/vaccination-detail.html"

@login_required
def appointment_letter(request, vaccination_id):
    vaccination = Vaccination.objects.get(id=vaccination_id)
    context = {
        "pdf_title": f"{vaccination.patient.get_full_name()} | Appointment Letter",
        "date": str(timezone.now()),
        "title": "Appointment Letter",
        "subtitle": "To Whom it may concern",
        "content": f"This is to inform that the {vaccination.campaign.vaccine.name} vaccination of Mr/Ms {vaccination.patient.get_full_name()} is scheduled on {vaccination.slot.date}",
    }
    return generate_pdf(context)

@login_required
def vaccination_certificate(request, vaccination_id):
    vaccination = Vaccination.objects.get(id=vaccination_id)
    if vaccination.is_vaccinated:
        context = {
            "pdf_title": f"{vaccination.patient.get_full_name()} | Vaccination Certificate",
            "date": str(timezone.now()),
            "title": "Vaccination Certificate",
            "subtitle": "To Whom it may concern",
            "content": f"This is to certify that Mr/Ms {vaccination.patient.get_full_name()} has successfully taken {vaccination.campaign.vaccine.name} on {vaccination.date}. The vaccination was scheduled on {vaccination.slot.date} {vaccination.slot.start_time} at {vaccination.campaign.center.name}.",
        }
        return generate_pdf(context)
    return HttpResponseBadRequest("User not vaccinated")


def approve_vaccination(request, vaccination_id):
    if request.user.has_perm("vaccination.change_vaccination"):
        try:
            vaccination = Vaccination.objects.get(id=vaccination_id)
        except Vaccination.DoesNotExist:
            return HttpResponseBadRequest("Vaccination with the given object id does not exists")
        
        if request.user in vaccination.campaign.agents.all():
            if vaccination.is_vaccinated:
                return HttpResponse("Patient is already Vaccinated")
            vaccination.is_vaccinated = True
            vaccination.date = timezone.now()
            vaccination.updated_by = request.user
            vaccination.save()
            return HttpResponseRedirect(reverse("vaccination:vaccination-detail", kwargs={"pk": vaccination_id}))
        raise PermissionDenied()
    raise PermissionDenied()

mysite/vaccination/templates/vaccination/choose-campaign.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Choose Campaign</title>
{% endblock title %}

{% block content %}
<div class="mt-3">
  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center">Choose Your Desired Campaign</h3>
  </div>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th scope="col">Center</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Confirm</th>
      </tr>
    </thead>
    
    <tbody>
      {% for campaign in page_obj %}
      <tr>
        <td>{{ campaign.center.name }}</td>
        <td>{{ campaign.start_date }}</td>
        <td>{{ campaign.end_date }}</td>
        <td><a href="{% url 'vaccination:choose-slot' campaign.id %}" class="btn-sm btn-outline-primary">Select</a></td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  {% include "components/pagination.html" %}

</div>
{% endblock content %}

mysite/vaccination/templates/vaccination/choose-slot.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Choose Slot</title>
{% endblock title %}

{% block content %}
<div class="mt-3">
  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center">Choose Your Desired Slot</h3>
  </div>
  <table class="table table-responsive table-hover">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Start Time'</th>
        <th scope="col">End Time</th>
        <th scope="col">Max Capacity</th>
        <th scope="col">Reserved</th>
        <th scope="col">Confirm</th>
      </tr>
    </thead>
    <tbody>
      {% for slot in page_obj %}
      <tr>
        <td>{{ slot.date }}</td>
        <td>{{ slot.start_time }}</td>
        <td>{{ slot.end_time }}</td>
        <td>{{ slot.max_capacity }}</td>
        <td>{{ slot.reserved }}</td>
        <td><a href="{% url 'vaccination:confirm-vaccination' slot.campaign.id slot.id %}" class="btn-sm btn-outline-primary">Choose</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include "components/pagination.html" %}

</div>
{% endblock content %}

mysite/vaccination/templates/vaccination/choose-vaccine.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Choose Vaccine</title>
{% endblock title %}

{% block content %}
<div class="mt-3">
  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center">Choose Your <i class="fas fa-syringe"></i> Vaccine</h3>
  </div>
  <table class="table table-responsive table-hover">

    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Number of Doses</th>
        <th scope="col">Interval</th>
        <th scope="col">Confirm</th>
      </tr>
    </thead>

    <tbody>
      {% for vaccine in page_obj %}
      <tr>
        <td>{{ vaccine.name|upper }}</td>
        <td>{{ vaccine.number_of_doses }}</td>
        <td>{{ vaccine.interval }}</td>
        <td><a href="{% url 'vaccination:choose-campaign' vaccine.id %}" class="btn-sm btn-outline-primary">Select</a></td>
      </tr>
      {% endfor %}
    </tbody>
    
  </table>

  {% include "components/pagination.html" %}

</div>
{% endblock content %}

mysite/vaccination/templates/vaccination/confirm-vaccination.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Confirm Vaccination</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4">
      <i class="fas fa-calendar"></i> Review the vaccination details
    </h5>
    <div class="container">
      <div class="row">

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Patient Name
          </div>
          <div class="col-7 col-md-8">
            {{ patient.get_full_name }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Email
          </div>
          <div class="col-7 col-md-8">
            {{ patient.email }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Gender
          </div>
          <div class="col-7 col-md-8">
            {{ patient.gender }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Date of Birth
          </div>
          <div class="col-7 col-md-8">
            {{ patient.date_of_birth }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Blood Group
          </div>
          <div class="col-7 col-md-8">
            {{ patient.blood_group }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            {{ patient.identity_document_type }}
          </div>
          <div class="col-7 col-md-8">
            {{ patient.identity_document_number }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Vaccine
          </div>
          <div class="col-7 col-md-8">
            {{ campaign.vaccine.name }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Scheduled Date
          </div>
          <div class="col-7 col-md-8">
            {{ slot.date }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Reporting Time
          </div>
          <div class="col-7 col-md-8">
            {{ slot.start_time }} - {{ slot.end_time}}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Center Name
          </div>
          <div class="col-7 col-md-8">
            {{ campaign.center.name }}
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-5 col-md-4 fw-bold">
            Center Address
          </div>
          <div class="col-7 col-md-8">
            {{ campaign.center.address}}
          </div>
        </div>

        <div class="row mb-1">
          <form method="POST" action="">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit" class="btn btn-success m-3">
              <i class="fas fa-clock"></i> Schedule
            </button>
          </form>
        </div>
        
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mysite/vaccination/templates/vaccination/vaccination-detail.html
{% extends 'mysite/base.html' %}

{% block title %} 
    <title>Vaccination List</title>
{% endblock title %}

{% block content %}
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title mb-4"><i class="fas fa-syringe"></i> Vaccination Details </h5>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Patient Name
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.patient.get_full_name }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Center Name
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.campaign.center.name }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Vaccine Name
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.campaign.vaccine.name }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Slot Date
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.slot.date }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Slot Time
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.slot.start_time }} to {{ object.slot.end_time }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Status
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {% if object.is_vaccinated %}
          Vaccinated
        {% else %}
          Scheduled
        {% endif %}
      </div>
    </div>

    {% if object.is_vaccinated %}
    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Date of Vaccination
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.date }}
      </div>
    </div>
    {% endif %}
    
    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Last Modified On
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.updated_on }}
      </div>
    </div>

    <div class="row mb-1">
      <div class="col-5 col-sm-4 col-md-3 col-lg-2 fw-bold">
        Last Updated By
      </div>
      <div class="col-7 col-sm-8 col-md-9 col-lg-10">
        {{ object.updated_by }}
      </div>
    </div>

    <div class="row mb-1 btn-container">
      <div class="col-12">
        <button class="btn btn-sm btn-primary m-1">
          <a href="{% url 'vaccination:appointment-letter' object.id %}"><i class="fas fa-download"></i> Appointment Letter</a>
        </button>

        {% if object.is_vaccinated %}
        <button class="btn btn-sm btn-success m-1">
            <a href="{% url 'vaccination:vaccination-certificate' object.id %}"><i class="fas fa-download"></i> Vaccine Certificate</a>
        </button>
        {% endif %}
      </div>
    </div>
    
  </div>
</div>
{% endblock content %}

mysite/vaccination/templates/vaccination/vaccination-list.html
{% extends 'mysite/base.html' %}

{% block title %}
    <title>Vaccination List</title>
{% endblock title %}

{% block content %}
<div class="mt-3">
  <div class="d-flex align-items-center justify-content-between">
    <h3 class="text-center"><i class="fas fa-syringe"></i> Your Vaccination History</h3>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Vaccine Name</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">Select</th>
      </tr>
    </thead>

    <tbody>
      {% for vaccination in object_list %}
        <tr>
            <td>{{ vaccination.campaign.vaccine.name|upper }}</a></td>
            <td>{{ vaccination.slot.date }}</td>
            
            <td>
                {% if vaccination.is_vaccinated %}
                    <button class="btn btn-sm btn-success">Vaccinated</button>
                {% else %}
                    <button class="btn btn-sm btn-primary">Scheduled</button>
                {% endif %}
            </td>
            <td><a href="{% url 'vaccination:vaccination-detail' vaccination.id %}" class="btn-sm btn-outline-primary">View Details</a></td>
        </tr>
      {% endfor %}
    </tbody>

  </table>

  {% include "components/pagination.html" %}

</div>
{% endblock content %}